//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulo()
        {
            this.ArticuloCriterio = new HashSet<ArticuloCriterio>();
            this.EvArticulo = new HashSet<EvArticulo>();
            this.ArtProveedor = new HashSet<ArtProveedor>();
        }
    
        public int ARTId { get; set; }
        public string SKU { get; set; }
        public string Nombre { get; set; }
        public string Estatus { get; set; }
        public string TipoProducto { get; set; }
        public string ClasificacionICA { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public string ClaveCategoria { get; set; }
        public string DescripcionCategoria { get; set; }
        public string ClaveSubCategoria { get; set; }
        public string DescripcionSubCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloCriterio> ArticuloCriterio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvArticulo> EvArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtProveedor> ArtProveedor { get; set; }
    }
}
