//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Criterio()
        {
            this.ArticuloCriterio = new HashSet<ArticuloCriterio>();
            this.EquipoCriterio = new HashSet<EquipoCriterio>();
            this.EvEquipo = new HashSet<EvEquipo>();
            this.EvArticulo = new HashSet<EvArticulo>();
        }
    
        public int CRTId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Clasificacion { get; set; }
        public bool Ev_Posterior { get; set; }
        public string TipoRespuesta { get; set; }
        public bool EvidenciaObli { get; set; }
        public int NoTomas { get; set; }
        public string TipoEquipo { get; set; }
        public bool Precargado { get; set; }
        public bool PermitirVacio { get; set; }
        public bool Comentario { get; set; }
        public bool Condicionante { get; set; }
        public Nullable<int> CRTId_Cond { get; set; }
        public string Estatus { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public string ValorReferencia { get; set; }
        public string EquipoProducto { get; set; }
        public string OperacionGlobal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloCriterio> ArticuloCriterio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoCriterio> EquipoCriterio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvEquipo> EvEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvArticulo> EvArticulo { get; set; }
    }
}
