//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacion()
        {
            this.EvArticulo = new HashSet<EvArticulo>();
            this.EvEquipo = new HashSet<EvEquipo>();
            this.ArtProveedor = new HashSet<ArtProveedor>();
        }
    
        public int EVAId { get; set; }
        public string ClaveTienda { get; set; }
        public string NombreTienda { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Zona { get; set; }
        public string Estatus { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public Nullable<int> PROId { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public string ZonaKiosko { get; set; }
        public string Region { get; set; }
    
        public virtual Programacion Programacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvArticulo> EvArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvEquipo> EvEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtProveedor> ArtProveedor { get; set; }
    }
}
