//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuloPerfil
    {
        public int PERId { get; set; }
        public int MODId { get; set; }
        public string Descripcion { get; set; }
        public byte Insertar { get; set; }
        public byte Leer { get; set; }
        public byte Actualizar { get; set; }
        public byte Borrar { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
