//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RangoTorqueVacio
    {
        public int RTVId { get; set; }
        public string Base { get; set; }
        public double ValorTorque { get; set; }
        public double TamGrano { get; set; }
        public double Resultado { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
        public string Estatus { get; set; }
    }
}
