//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProducto
    {
        public int TPRId { get; set; }
        public string Producto { get; set; }
        public string Categoria { get; set; }
        public Nullable<double> TamPorcion { get; set; }
        public string Unidad { get; set; }
        public Nullable<double> TamPorcionMin { get; set; }
        public string Estatus { get; set; }
        public System.DateTime MFechaHora { get; set; }
        public string MUsuarioId { get; set; }
    }
}
