//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICA.ServiceReferenceUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP.LDAP")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GrupoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsValido {
            get {
                return this.EsValidoField;
            }
            set {
                if ((this.EsValidoField.Equals(value) != true)) {
                    this.EsValidoField = value;
                    this.RaisePropertyChanged("EsValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grupo {
            get {
                return this.GrupoField;
            }
            set {
                if ((object.ReferenceEquals(this.GrupoField, value) != true)) {
                    this.GrupoField = value;
                    this.RaisePropertyChanged("Grupo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Proveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendID {
            get {
                return this.VendIDField;
            }
            set {
                if ((object.ReferenceEquals(this.VendIDField, value) != true)) {
                    this.VendIDField = value;
                    this.RaisePropertyChanged("VendID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zona", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Zona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tienda", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Tienda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SiteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ZonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SiteId {
            get {
                return this.SiteIdField;
            }
            set {
                if ((this.SiteIdField.Equals(value) != true)) {
                    this.SiteIdField = value;
                    this.RaisePropertyChanged("SiteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ZonaId {
            get {
                return this.ZonaIdField;
            }
            set {
                if ((this.ZonaIdField.Equals(value) != true)) {
                    this.ZonaIdField = value;
                    this.RaisePropertyChanged("ZonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaSubCategoria", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class CategoriaSubCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoriaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoria {
            get {
                return this.SubCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoriaField, value) != true)) {
                    this.SubCategoriaField = value;
                    this.RaisePropertyChanged("SubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoriaId {
            get {
                return this.SubCategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoriaIdField, value) != true)) {
                    this.SubCategoriaIdField = value;
                    this.RaisePropertyChanged("SubCategoriaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromocionesHeaderZona", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class PromocionesHeaderZona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCategoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDDepartamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDDivisionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDZonasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MecanicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PE_ActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PE_TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PE_TipoMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PE_ValorMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZonasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categorias {
            get {
                return this.CategoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriasField, value) != true)) {
                    this.CategoriasField = value;
                    this.RaisePropertyChanged("Categorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamentos {
            get {
                return this.DepartamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentosField, value) != true)) {
                    this.DepartamentosField = value;
                    this.RaisePropertyChanged("Departamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Divisiones {
            get {
                return this.DivisionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionesField, value) != true)) {
                    this.DivisionesField = value;
                    this.RaisePropertyChanged("Divisiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCategorias {
            get {
                return this.IDCategoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCategoriasField, value) != true)) {
                    this.IDCategoriasField = value;
                    this.RaisePropertyChanged("IDCategorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDDepartamentos {
            get {
                return this.IDDepartamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.IDDepartamentosField, value) != true)) {
                    this.IDDepartamentosField = value;
                    this.RaisePropertyChanged("IDDepartamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDDivisiones {
            get {
                return this.IDDivisionesField;
            }
            set {
                if ((object.ReferenceEquals(this.IDDivisionesField, value) != true)) {
                    this.IDDivisionesField = value;
                    this.RaisePropertyChanged("IDDivisiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDZonas {
            get {
                return this.IDZonasField;
            }
            set {
                if ((object.ReferenceEquals(this.IDZonasField, value) != true)) {
                    this.IDZonasField = value;
                    this.RaisePropertyChanged("IDZonas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mecanica {
            get {
                return this.MecanicaField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicaField, value) != true)) {
                    this.MecanicaField = value;
                    this.RaisePropertyChanged("Mecanica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PE_Activa {
            get {
                return this.PE_ActivaField;
            }
            set {
                if ((this.PE_ActivaField.Equals(value) != true)) {
                    this.PE_ActivaField = value;
                    this.RaisePropertyChanged("PE_Activa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_Codigo {
            get {
                return this.PE_CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_CodigoField, value) != true)) {
                    this.PE_CodigoField = value;
                    this.RaisePropertyChanged("PE_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_Descripcion {
            get {
                return this.PE_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_DescripcionField, value) != true)) {
                    this.PE_DescripcionField = value;
                    this.RaisePropertyChanged("PE_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PE_Tipo {
            get {
                return this.PE_TipoField;
            }
            set {
                if ((this.PE_TipoField.Equals(value) != true)) {
                    this.PE_TipoField = value;
                    this.RaisePropertyChanged("PE_Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PE_TipoMeta {
            get {
                return this.PE_TipoMetaField;
            }
            set {
                if ((this.PE_TipoMetaField.Equals(value) != true)) {
                    this.PE_TipoMetaField = value;
                    this.RaisePropertyChanged("PE_TipoMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PE_ValorMeta {
            get {
                return this.PE_ValorMetaField;
            }
            set {
                if ((this.PE_ValorMetaField.Equals(value) != true)) {
                    this.PE_ValorMetaField = value;
                    this.RaisePropertyChanged("PE_ValorMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zonas {
            get {
                return this.ZonasField;
            }
            set {
                if ((object.ReferenceEquals(this.ZonasField, value) != true)) {
                    this.ZonasField = value;
                    this.RaisePropertyChanged("Zonas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromocionesHeaderTienda", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class PromocionesHeaderTienda : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCategoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDDepartamentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDDivisionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MecanicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PE_ActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PE_TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PE_TipoMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PE_ValorMetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TiendasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categorias {
            get {
                return this.CategoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriasField, value) != true)) {
                    this.CategoriasField = value;
                    this.RaisePropertyChanged("Categorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamentos {
            get {
                return this.DepartamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentosField, value) != true)) {
                    this.DepartamentosField = value;
                    this.RaisePropertyChanged("Departamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Divisiones {
            get {
                return this.DivisionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionesField, value) != true)) {
                    this.DivisionesField = value;
                    this.RaisePropertyChanged("Divisiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCategorias {
            get {
                return this.IDCategoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCategoriasField, value) != true)) {
                    this.IDCategoriasField = value;
                    this.RaisePropertyChanged("IDCategorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDDepartamentos {
            get {
                return this.IDDepartamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.IDDepartamentosField, value) != true)) {
                    this.IDDepartamentosField = value;
                    this.RaisePropertyChanged("IDDepartamentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDDivisiones {
            get {
                return this.IDDivisionesField;
            }
            set {
                if ((object.ReferenceEquals(this.IDDivisionesField, value) != true)) {
                    this.IDDivisionesField = value;
                    this.RaisePropertyChanged("IDDivisiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mecanica {
            get {
                return this.MecanicaField;
            }
            set {
                if ((object.ReferenceEquals(this.MecanicaField, value) != true)) {
                    this.MecanicaField = value;
                    this.RaisePropertyChanged("Mecanica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PE_Activa {
            get {
                return this.PE_ActivaField;
            }
            set {
                if ((this.PE_ActivaField.Equals(value) != true)) {
                    this.PE_ActivaField = value;
                    this.RaisePropertyChanged("PE_Activa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_Codigo {
            get {
                return this.PE_CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_CodigoField, value) != true)) {
                    this.PE_CodigoField = value;
                    this.RaisePropertyChanged("PE_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_Descripcion {
            get {
                return this.PE_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_DescripcionField, value) != true)) {
                    this.PE_DescripcionField = value;
                    this.RaisePropertyChanged("PE_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PE_Tipo {
            get {
                return this.PE_TipoField;
            }
            set {
                if ((this.PE_TipoField.Equals(value) != true)) {
                    this.PE_TipoField = value;
                    this.RaisePropertyChanged("PE_Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PE_TipoMeta {
            get {
                return this.PE_TipoMetaField;
            }
            set {
                if ((this.PE_TipoMetaField.Equals(value) != true)) {
                    this.PE_TipoMetaField = value;
                    this.RaisePropertyChanged("PE_TipoMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PE_ValorMeta {
            get {
                return this.PE_ValorMetaField;
            }
            set {
                if ((this.PE_ValorMetaField.Equals(value) != true)) {
                    this.PE_ValorMetaField = value;
                    this.RaisePropertyChanged("PE_ValorMeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tiendas {
            get {
                return this.TiendasField;
            }
            set {
                if ((object.ReferenceEquals(this.TiendasField, value) != true)) {
                    this.TiendasField = value;
                    this.RaisePropertyChanged("Tiendas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromocionesDetail", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class PromocionesDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Art_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PED_ArtOrgCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PED_TipoArtOrgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PED_TipoDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PED_ValorDescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Art_Descripcion {
            get {
                return this.Art_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.Art_DescripcionField, value) != true)) {
                    this.Art_DescripcionField = value;
                    this.RaisePropertyChanged("Art_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((this.CategoriaField.Equals(value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Depto {
            get {
                return this.DeptoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptoField, value) != true)) {
                    this.DeptoField = value;
                    this.RaisePropertyChanged("Depto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PED_ArtOrgCodigo {
            get {
                return this.PED_ArtOrgCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.PED_ArtOrgCodigoField, value) != true)) {
                    this.PED_ArtOrgCodigoField = value;
                    this.RaisePropertyChanged("PED_ArtOrgCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PED_TipoArtOrg {
            get {
                return this.PED_TipoArtOrgField;
            }
            set {
                if ((this.PED_TipoArtOrgField.Equals(value) != true)) {
                    this.PED_TipoArtOrgField = value;
                    this.RaisePropertyChanged("PED_TipoArtOrg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PED_TipoDescuento {
            get {
                return this.PED_TipoDescuentoField;
            }
            set {
                if ((this.PED_TipoDescuentoField.Equals(value) != true)) {
                    this.PED_TipoDescuentoField = value;
                    this.RaisePropertyChanged("PED_TipoDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PED_ValorDescuento {
            get {
                return this.PED_ValorDescuentoField;
            }
            set {
                if ((this.PED_ValorDescuentoField.Equals(value) != true)) {
                    this.PED_ValorDescuentoField = value;
                    this.RaisePropertyChanged("PED_ValorDescuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_Codigo {
            get {
                return this.PE_CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_CodigoField, value) != true)) {
                    this.PE_CodigoField = value;
                    this.RaisePropertyChanged("PE_Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubCategoria {
            get {
                return this.SubCategoriaField;
            }
            set {
                if ((this.SubCategoriaField.Equals(value) != true)) {
                    this.SubCategoriaField = value;
                    this.RaisePropertyChanged("SubCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoPromocion", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class TipoPromocion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PE_TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PE_TipoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PE_Tipo {
            get {
                return this.PE_TipoField;
            }
            set {
                if ((this.PE_TipoField.Equals(value) != true)) {
                    this.PE_TipoField = value;
                    this.RaisePropertyChanged("PE_Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PE_TipoDescripcion {
            get {
                return this.PE_TipoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.PE_TipoDescripcionField, value) != true)) {
                    this.PE_TipoDescripcionField = value;
                    this.RaisePropertyChanged("PE_TipoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Divisiones", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Divisiones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Division {
            get {
                return this.DivisionField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionField, value) != true)) {
                    this.DivisionField = value;
                    this.RaisePropertyChanged("Division");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionId {
            get {
                return this.DivisionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionIdField, value) != true)) {
                    this.DivisionIdField = value;
                    this.RaisePropertyChanged("DivisionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamentos", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Departamentos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoIdField, value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionId {
            get {
                return this.DivisionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionIdField, value) != true)) {
                    this.DivisionIdField = value;
                    this.RaisePropertyChanged("DivisionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categorias", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class Categorias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCatFullField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoIdField, value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionId {
            get {
                return this.DivisionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionIdField, value) != true)) {
                    this.DivisionIdField = value;
                    this.RaisePropertyChanged("DivisionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCatFull {
            get {
                return this.IdCatFullField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCatFullField, value) != true)) {
                    this.IdCatFullField = value;
                    this.RaisePropertyChanged("IdCatFull");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubCategorias", Namespace="http://schemas.datacontract.org/2004/07/WcfLoginLDAP")]
    [System.SerializableAttribute()]
    public partial class SubCategorias : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoriaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DivisionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdSubCatFullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCategoriaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria {
            get {
                return this.CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaField, value) != true)) {
                    this.CategoriaField = value;
                    this.RaisePropertyChanged("Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartamentoId {
            get {
                return this.DepartamentoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoIdField, value) != true)) {
                    this.DepartamentoIdField = value;
                    this.RaisePropertyChanged("DepartamentoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DivisionId {
            get {
                return this.DivisionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionIdField, value) != true)) {
                    this.DivisionIdField = value;
                    this.RaisePropertyChanged("DivisionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdSubCatFull {
            get {
                return this.IdSubCatFullField;
            }
            set {
                if ((object.ReferenceEquals(this.IdSubCatFullField, value) != true)) {
                    this.IdSubCatFullField = value;
                    this.RaisePropertyChanged("IdSubCatFull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoria {
            get {
                return this.SubCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoriaField, value) != true)) {
                    this.SubCategoriaField = value;
                    this.RaisePropertyChanged("SubCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategoriaId {
            get {
                return this.SubCategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoriaIdField, value) != true)) {
                    this.SubCategoriaIdField = value;
                    this.RaisePropertyChanged("SubCategoriaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuarios.ILogin")]
    public interface ILogin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetData", ReplyAction="http://tempuri.org/ILogin/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetData", ReplyAction="http://tempuri.org/ILogin/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/Autenticar", ReplyAction="http://tempuri.org/ILogin/AutenticarResponse")]
        ICA.ServiceReferenceUsuarios.Usuario Autenticar(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/Autenticar", ReplyAction="http://tempuri.org/ILogin/AutenticarResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Usuario> AutenticarAsync(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTodosUsuarios", ReplyAction="http://tempuri.org/ILogin/ObtenerTodosUsuariosResponse")]
        ICA.ServiceReferenceUsuarios.Usuario[] ObtenerTodosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTodosUsuarios", ReplyAction="http://tempuri.org/ILogin/ObtenerTodosUsuariosResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Usuario[]> ObtenerTodosUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTodosProveedores", ReplyAction="http://tempuri.org/ILogin/ObtenerTodosProveedoresResponse")]
        ICA.ServiceReferenceUsuarios.Proveedor[] ObtenerTodosProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTodosProveedores", ReplyAction="http://tempuri.org/ILogin/ObtenerTodosProveedoresResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Proveedor[]> ObtenerTodosProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerZonas", ReplyAction="http://tempuri.org/ILogin/ObtenerZonasResponse")]
        ICA.ServiceReferenceUsuarios.Zona[] ObtenerZonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerZonas", ReplyAction="http://tempuri.org/ILogin/ObtenerZonasResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Zona[]> ObtenerZonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTiendas", ReplyAction="http://tempuri.org/ILogin/ObtenerTiendasResponse")]
        ICA.ServiceReferenceUsuarios.Tienda[] ObtenerTiendas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerTiendas", ReplyAction="http://tempuri.org/ILogin/ObtenerTiendasResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Tienda[]> ObtenerTiendasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerCategoriasSubCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerCategoriasSubCategoriasResponse")]
        ICA.ServiceReferenceUsuarios.CategoriaSubCategoria[] ObtenerCategoriasSubCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerCategoriasSubCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerCategoriasSubCategoriasResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.CategoriaSubCategoria[]> ObtenerCategoriasSubCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesByZona", ReplyAction="http://tempuri.org/ILogin/GetPromocionesByZonaResponse")]
        ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[] GetPromocionesByZona(System.DateTime FechaIni, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesByZona", ReplyAction="http://tempuri.org/ILogin/GetPromocionesByZonaResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[]> GetPromocionesByZonaAsync(System.DateTime FechaIni, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesByTienda", ReplyAction="http://tempuri.org/ILogin/GetPromocionesByTiendaResponse")]
        ICA.ServiceReferenceUsuarios.PromocionesHeaderTienda[] GetPromocionesByTienda(System.DateTime FechaIni, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesByTienda", ReplyAction="http://tempuri.org/ILogin/GetPromocionesByTiendaResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderTienda[]> GetPromocionesByTiendaAsync(System.DateTime FechaIni, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesDetail", ReplyAction="http://tempuri.org/ILogin/GetPromocionesDetailResponse")]
        ICA.ServiceReferenceUsuarios.PromocionesDetail[] GetPromocionesDetail(string PE_Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetPromocionesDetail", ReplyAction="http://tempuri.org/ILogin/GetPromocionesDetailResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesDetail[]> GetPromocionesDetailAsync(string PE_Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetTipoPromociones", ReplyAction="http://tempuri.org/ILogin/GetTipoPromocionesResponse")]
        ICA.ServiceReferenceUsuarios.TipoPromocion[] GetTipoPromociones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/GetTipoPromociones", ReplyAction="http://tempuri.org/ILogin/GetTipoPromocionesResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.TipoPromocion[]> GetTipoPromocionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerPeriodoPromocional", ReplyAction="http://tempuri.org/ILogin/ObtenerPeriodoPromocionalResponse")]
        System.DateTime ObtenerPeriodoPromocional(string PE_Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerPeriodoPromocional", ReplyAction="http://tempuri.org/ILogin/ObtenerPeriodoPromocionalResponse")]
        System.Threading.Tasks.Task<System.DateTime> ObtenerPeriodoPromocionalAsync(string PE_Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDivisiones", ReplyAction="http://tempuri.org/ILogin/ObtenerDivisionesResponse")]
        ICA.ServiceReferenceUsuarios.Divisiones[] ObtenerDivisiones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDivisiones", ReplyAction="http://tempuri.org/ILogin/ObtenerDivisionesResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Divisiones[]> ObtenerDivisionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDepartamentos", ReplyAction="http://tempuri.org/ILogin/ObtenerDepartamentosResponse")]
        ICA.ServiceReferenceUsuarios.Departamentos[] ObtenerDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDepartamentos", ReplyAction="http://tempuri.org/ILogin/ObtenerDepartamentosResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Departamentos[]> ObtenerDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerCategoriasResponse")]
        ICA.ServiceReferenceUsuarios.Categorias[] ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerCategoriasResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Categorias[]> ObtenerCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDeptoCategoriasSubCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerDeptoCategoriasSubCategoriasResponse")]
        ICA.ServiceReferenceUsuarios.SubCategorias[] ObtenerDeptoCategoriasSubCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerDeptoCategoriasSubCategorias", ReplyAction="http://tempuri.org/ILogin/ObtenerDeptoCategoriasSubCategoriasResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.SubCategorias[]> ObtenerDeptoCategoriasSubCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerPromocionesByPECodigo", ReplyAction="http://tempuri.org/ILogin/ObtenerPromocionesByPECodigoResponse")]
        ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[] ObtenerPromocionesByPECodigo(System.DateTime FechaIni, System.DateTime FechaFin, string ListPECodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogin/ObtenerPromocionesByPECodigo", ReplyAction="http://tempuri.org/ILogin/ObtenerPromocionesByPECodigoResponse")]
        System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[]> ObtenerPromocionesByPECodigoAsync(System.DateTime FechaIni, System.DateTime FechaFin, string ListPECodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginChannel : ICA.ServiceReferenceUsuarios.ILogin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginClient : System.ServiceModel.ClientBase<ICA.ServiceReferenceUsuarios.ILogin>, ICA.ServiceReferenceUsuarios.ILogin {
        
        public LoginClient() {
        }
        
        public LoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ICA.ServiceReferenceUsuarios.Usuario Autenticar(string usuario, string contraseña) {
            return base.Channel.Autenticar(usuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Usuario> AutenticarAsync(string usuario, string contraseña) {
            return base.Channel.AutenticarAsync(usuario, contraseña);
        }
        
        public ICA.ServiceReferenceUsuarios.Usuario[] ObtenerTodosUsuarios() {
            return base.Channel.ObtenerTodosUsuarios();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Usuario[]> ObtenerTodosUsuariosAsync() {
            return base.Channel.ObtenerTodosUsuariosAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.Proveedor[] ObtenerTodosProveedores() {
            return base.Channel.ObtenerTodosProveedores();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Proveedor[]> ObtenerTodosProveedoresAsync() {
            return base.Channel.ObtenerTodosProveedoresAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.Zona[] ObtenerZonas() {
            return base.Channel.ObtenerZonas();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Zona[]> ObtenerZonasAsync() {
            return base.Channel.ObtenerZonasAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.Tienda[] ObtenerTiendas() {
            return base.Channel.ObtenerTiendas();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Tienda[]> ObtenerTiendasAsync() {
            return base.Channel.ObtenerTiendasAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.CategoriaSubCategoria[] ObtenerCategoriasSubCategorias() {
            return base.Channel.ObtenerCategoriasSubCategorias();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.CategoriaSubCategoria[]> ObtenerCategoriasSubCategoriasAsync() {
            return base.Channel.ObtenerCategoriasSubCategoriasAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[] GetPromocionesByZona(System.DateTime FechaIni, System.DateTime FechaFin) {
            return base.Channel.GetPromocionesByZona(FechaIni, FechaFin);
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[]> GetPromocionesByZonaAsync(System.DateTime FechaIni, System.DateTime FechaFin) {
            return base.Channel.GetPromocionesByZonaAsync(FechaIni, FechaFin);
        }
        
        public ICA.ServiceReferenceUsuarios.PromocionesHeaderTienda[] GetPromocionesByTienda(System.DateTime FechaIni, System.DateTime FechaFin) {
            return base.Channel.GetPromocionesByTienda(FechaIni, FechaFin);
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderTienda[]> GetPromocionesByTiendaAsync(System.DateTime FechaIni, System.DateTime FechaFin) {
            return base.Channel.GetPromocionesByTiendaAsync(FechaIni, FechaFin);
        }
        
        public ICA.ServiceReferenceUsuarios.PromocionesDetail[] GetPromocionesDetail(string PE_Codigo) {
            return base.Channel.GetPromocionesDetail(PE_Codigo);
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesDetail[]> GetPromocionesDetailAsync(string PE_Codigo) {
            return base.Channel.GetPromocionesDetailAsync(PE_Codigo);
        }
        
        public ICA.ServiceReferenceUsuarios.TipoPromocion[] GetTipoPromociones() {
            return base.Channel.GetTipoPromociones();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.TipoPromocion[]> GetTipoPromocionesAsync() {
            return base.Channel.GetTipoPromocionesAsync();
        }
        
        public System.DateTime ObtenerPeriodoPromocional(string PE_Codigo) {
            return base.Channel.ObtenerPeriodoPromocional(PE_Codigo);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> ObtenerPeriodoPromocionalAsync(string PE_Codigo) {
            return base.Channel.ObtenerPeriodoPromocionalAsync(PE_Codigo);
        }
        
        public ICA.ServiceReferenceUsuarios.Divisiones[] ObtenerDivisiones() {
            return base.Channel.ObtenerDivisiones();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Divisiones[]> ObtenerDivisionesAsync() {
            return base.Channel.ObtenerDivisionesAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.Departamentos[] ObtenerDepartamentos() {
            return base.Channel.ObtenerDepartamentos();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Departamentos[]> ObtenerDepartamentosAsync() {
            return base.Channel.ObtenerDepartamentosAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.Categorias[] ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.Categorias[]> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.SubCategorias[] ObtenerDeptoCategoriasSubCategorias() {
            return base.Channel.ObtenerDeptoCategoriasSubCategorias();
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.SubCategorias[]> ObtenerDeptoCategoriasSubCategoriasAsync() {
            return base.Channel.ObtenerDeptoCategoriasSubCategoriasAsync();
        }
        
        public ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[] ObtenerPromocionesByPECodigo(System.DateTime FechaIni, System.DateTime FechaFin, string ListPECodigo) {
            return base.Channel.ObtenerPromocionesByPECodigo(FechaIni, FechaFin, ListPECodigo);
        }
        
        public System.Threading.Tasks.Task<ICA.ServiceReferenceUsuarios.PromocionesHeaderZona[]> ObtenerPromocionesByPECodigoAsync(System.DateTime FechaIni, System.DateTime FechaFin, string ListPECodigo) {
            return base.Channel.ObtenerPromocionesByPECodigoAsync(FechaIni, FechaFin, ListPECodigo);
        }
    }
}
